src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User Implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $level;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $password;

     /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;
/**
 * @ORM\Column(type="json")
 */
private $roles = array();
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(?string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }
    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }
    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }
    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }
    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function getRoles()
    {
        return $this->roles;
    }
    
    public function setRoles(array $roles)
    {
        $this->roles = $roles;
    
        // allows for chaining
        return $this;
    }
    public function getSalt(){}
    public function eraseCredentials(){}
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;

class ReclamationType extends AbstractType
{
    /**
     * {@inheritDoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content',TextareaType::class,[

                'attr'=>[
                    'rows'=>'5',
                    'id'=>'message_contact',

                    'class'=>'form-control styled',
                    'style'=>'height:100px;',
                    'placeholder'=>'Hello world!'
                ]
            ])
        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

templates/reclamations/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <!-- SubHeader =============================================== -->
    <section class="parallax_window_in" data-parallax="scroll" data-image-src="{{ asset('front/img/sub_header_general.jpg') }}" data-natural-width="1400" data-natural-height="470">
        <div id="sub_content_in">
            <h1>LoveFit Blog</h1>
            <p>"Usu habeo equidem sanctus no ex melius labitur conceptam eos"</p>
        </div>
    </section>
    <!-- End section -->
    <!-- End SubHeader ============================================ -->
    <div class="container margin_60_35">
        <div class="row">

            <div class="col-md-9">
                <h3>Contact us</h3>
                <p>
                    Mussum ipsum cacilds, vidis litro abertis.
                </p>
                <div>
                    <div id="message-contact"></div>
                    {{  form_start(form,{'attr':{'novalidate': 'novalidate','id':'contactform'}}) }}
                        <div class="row">
                            <div class="col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>First name</label>
                                    <input type="text" class="form-control styled" id="name_contact" name="name_contact" placeholder="{{ user.firstName }}" disabled>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Last name</label>
                                    <input type="text" class="form-control styled" id="lastname_contact" name="lastname_contact" placeholder="{{ user.firstName }}" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Email:</label>
                                    <input type="email" id="email_contact" name="email_contact" class="form-control styled" placeholder="{{ user.email }}"disabled>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Phone number:</label>
                                    <input type="text" id="phone_contact" name="phone_contact" class="form-control styled" placeholder="{{ user.phone }}"disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Your message:</label>
                                    {{ form_widget(form.content) }}
                                    {{ form_errors(form.content) }}
                                    <!--<textarea rows="5" id="message_contact" name="message_contact" class="form-control styled" style="height:100px;" placeholder="Hello world!"></textarea>-->
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <!--<div class="form-group">
                                    <label>Are you human? 3 + 1 =</label>
                                    <input type="text" id="verify_contact" class=" form-control styled" placeholder=" 3 + 1 =">
                                </div>-->
                                <p><input type="submit" value="Submit" class="btn_1" id="submit-contact"></p>
                            </div>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
            <!-- End col lg 9 -->
            <aside class="col-md-3">
                <div class="box_style_2">
                    <h4>Contacts info</h4>
                    <p>
                        11 Fifth Ave - New York, US
                        <br> + 61 (2) 8093 3400
                        <br>
                        <a href="#">info@domain.com</a>
                    </p>
                    <h5>Get directions</h5>
                    <form action="http://maps.google.com/maps" method="get" target="_blank">
                        <div class="form-group">
                            <input type="text" name="saddr" placeholder="Enter your location" class="form-control styled">
                            <input type="hidden" name="daddr" value="New York, NY 11430">
                            <!-- Write here your end point -->
                        </div>
                        <input type="submit" value="Get directions" class="btn_1 add_bottom_15">
                    </form>
                    <hr class="styled">
                    <h4>Departmens</h4>
                    <ul class="contacts_info">
                        <li>Administration
                            <br>
                            <a href="tel://003823932342">0038 23932342</a>
                            <br><a href="tel://003823932342">admin@lovefit.com</a>
                            <br>
                            <small>Monday to Friday 9am - 7pm</small>
                        </li>
                        <li>General questions
                            <br>
                            <a href="tel://003823932342">0038 23932342</a>
                            <br><a href="tel://003823932342">questions@lovefit.com</a>
                            <br>
                            <small>Monday to Friday 9am - 7pm</small>
                        </li>
                    </ul>
                </div>
            </aside>
            <!--End aside -->
        </div>
        <!-- End row -->
    </div>
    <!-- End container -->

    <div id="map_contact"></div>
    <!-- end map-->
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="{{ asset('front/js/mapmarker.jquery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('front/js/mapmarker_func.jquery.js') }}"></script>
{% endblock %}